import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="format-detection" content="telephone=no" />
        <link rel="icon" href="/images/favicon.png" type="image/x-icon" />

        {/* Stylesheets */}
        <link rel="stylesheet" href="/vendor/slick/slick.css" />
        <link rel="stylesheet" href="/vendor/animate/animate.min.css" />
        <link rel="stylesheet" href="/icons/style.css" />
        <link
          rel="stylesheet"
          href="/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.css"
        />



{/* Stylesheets */}

<link href="vendor2/slick/slick.css" rel="stylesheet" />
<link href="vendor2/animate/animate.min.css" rel="stylesheet" />
<link href="icons/style.css" rel="stylesheet" />
<link
  href="vendor2/bootstrap-datetimepicker/bootstrap-datetimepicker.css"
  rel="stylesheet"
/>
<link href="css2/style.css" rel="stylesheet" />
<link href="color/color.css" rel="stylesheet" />





        <link rel="stylesheet" href="/css/style.css" />
        <link rel="stylesheet" href="/color/color.css" />

        {/* Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Google Maps Script */}
        <Script
          src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"
          strategy="afterInteractive"
        />

        {/* <!-- Vendors --> */}
        <Script src="vendor/jquery/jquery-3.2.1.min.js"></Script>
        <Script src="vendor/jquery-migrate/jquery-migrate-3.0.1.min.js"></Script>
        <Script src="vendor/cookie/jquery.cookie.js"></Script>
        <Script src="vendor/bootstrap-datetimepicker/moment.js"></Script>
        <Script src="vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></Script>
        <Script src="vendor/popper/popper.min.js"></Script>
        <Script src="vendor/bootstrap/bootstrap.min.js"></Script>
        <Script src="vendor/waypoints/jquery.waypoints.min.js"></Script>
        <Script src="vendor/waypoints/sticky.min.js"></Script>
        <Script src="vendor/imagesloaded/imagesloaded.pkgd.min.js"></Script>
        <Script src="vendor/slick/slick.min.js"></Script>
        <Script src="vendor/scroll-with-ease/jquery.scroll-with-ease.min.js"></Script>
        <Script src="vendor/countTo/jquery.countTo.js"></Script>
        <Script src="vendor/form-validation/jquery.form.js"></Script>
        <Script src="vendor/form-validation/jquery.validate.min.js"></Script>
        {/* <!-- Custom Scripts --> */}
        <Script src="js/app.js"></Script>
        <Script src="color/color.js"></Script>

        <Script src="js/app-shop.js"></Script>
        <Script src="form/forms.js"></Script>



{/* <!-- Vendors --> */}
<script src="vendor2/jquery/jquery-3.2.1.min.js"></script>
<script src="vendor2/jquery-migrate/jquery-migrate-3.0.1.min.js"></script>
<script src="vendor2/cookie/jquery.cookie.js"></script>
<script src="vendor2/bootstrap-datetimepicker/moment.js"></script>
<script src="vendor2/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></script>
<script src="vendor2/popper/popper.min.js"></script>
<script src="vendor2/bootstrap/bootstrap.min.js"></script>
<script src="vendor2/waypoints/jquery.waypoints.min.js"></script>
<script src="vendor2/waypoints/sticky.min.js"></script>
<script src="vendor2/imagesloaded/imagesloaded.pkgd.min.js"></script>
{/* <script src="vendor2/slick/slick.min.js"></script> */}
<script src="vendor2/scroll-with-ease/jquery.scroll-with-ease.min.js"></script>
<script src="vendor2/countTo/jquery.countTo.js"></script>
<script src="vendor2/form-validation/jquery.form.js"></script>
<script src="vendor2/form-validation/jquery.validate.min.js"></script>
<script src="vendor2/isotope/isotope.pkgd.min.js"></script>
{/* <!-- Custom Scripts --> */}
<script src="js2/app.js"></script><script src="/color/color.js"></script>
<script src="js2/bmi-calculator.js"></script>
<script src="js2/app-shop.js"></script>
<script src="form/forms.js"></script>



      </body>
    </html>
  );
}
